openapi: 3.0.2

info:
  version: '3.0.0-alpha'
  title: Violet User System Internal APIs
  description: Violet用户授权系统内部API列表
  termsOfService: 'https://xmatrix.studio/terms'
  contact:
    name: XMatrix Studio
    url: 'https://oauth.xmatrix.studio/support'
    email: 'a@xmatrix.studio'
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'

servers:
- url: 'https://oauth.xmatrix.studio/api/v3/i'
  description: XMatrix OAuth APIs
- url: 'https://test.xmatrix.studio/api/violet/v3/i/'
  description: XMatrix OAuth Test APIs
- url: 'localhost:40002/i/'
  description: XMatrix OAuth Localhost APIs

tags:
- name: Administration
  description: 与管理相关的接口，包括申请审核等
- name: Applications
  description: 与应用相关的接口，包括创建、修改、删除、授权等
- name: Organizations
  description: 与组织相关的接口，包括创建、修改、删除等
- name: Users
  description: 与用户相关的接口，包括注册、登陆、登出等
- name: Util
  description: 工具类接口，包括获取图形验证码等

components:
  # schemas:
  responses:
    401NotLoginError:
      description: 身份验证未通过
      content:
        'application/json':
          schema:
            type: object
            properties:
              error:
                type: string
                description: |
                  invalid_token - 未进行身份验证<br>
                  timeout_token - 身份验证已过期<br>
                example: 'invalid_token'
    403PermissionDenyError:
      description: 权限不足
      content:
        'application/json':
          schema:
            type: object
            properties:
              error:
                type: string
                description: |
                  permission_deny - 权限不足<br>
                example: 'permission_deny'
  # parameters:
  # examples:
  # requestBodies:
  # headers:
  # securitySchemas:
  # links:
  # callbacks:

paths:
  '/admin/requests':
    get:
      tags: [Administration]
      summary: 获取申请列表
      description: |
        权限要求：管理员以上。<br>
        分页获取申请列表，可用于所有用户的申请记录列表。<br>
      parameters:
      - name: page
        in: query
        required: true
        description: 页数
        schema:
          type: number
          minimum: 1
      - name: limit
        in: query
        required: true
        description: 每页资源数量
        schema:
          type: number
          minimum: 1
      - name: type
        in: query
        description: |
          申请类型筛选<br>
          0 - 开发者权限<br>
          1 - 管理员权限<br>
          10 - 用户应用上限<br>
          11 - 用户组织上限<br>
          20 - 组织应用上限<br>
          该参数为空时获取所有类型申请<br>
        schema:
          type: number
      - name: state
        in: query
        description: |
          申请状态筛选<br>
          0 - 待审核<br>
          1 - 已通过<br>
          2 - 已拒绝<br>
          该参数为空时获取所有状态申请<br>
        schema:
          type: number
      responses:
        '200':
          description: 获取成功
          content:
            'application/json':
              schema:
                type: object
                properties:
                  pagination:
                    type: object
                    description: 分页获取信息
                    properties:
                      page:
                        type: number
                        description: 当前页
                        example: 1
                      limit:
                        type: number
                        description: 每页资源数量
                        example: 5
                      total:
                        type: number
                        description: 资源总数
                        example: 1
                  data:
                    type: array
                    description: 申请记录集合
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: 用户名
                          example: 'XMatrix'
                        type:
                          type: number
                          description: |
                            申请类型<br>
                            0 - 开发者权限<br>
                            1 - 管理员权限<br>
                            10 - 用户应用上限<br>
                            11 - 用户组织上限<br>
                            20 - 组织应用上限<br>
                          example: 1
                        remark:
                          type: string
                          description: 备注
                          example: 'I am boss.'
                        time:
                          type: string
                          description: 申请时间
                          format: date-time
                        state:
                          type: number
                          description: |
                            申请状态<br>
                            0 - 待审核<br>
                            1 - 已通过<br>
                            2 - 已拒绝<br>
                          example: 0
        '400':
          description: 获取失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      invalid_limit - 非法每页资源数<br>
                      invalid_page - 非法页码<br>
                      invalid_state - 非法状态<br>
                      invalid_type - 非法类型<br>
                    example: 'invalid_state'
        '401':
          $ref: '#/components/responses/401NotLoginError'
        '403':
          $ref: '#/components/responses/403PermissionDenyError'

  '/apps':
    post:
      tags: [Applications]
      summary: 新建应用
      description: |
        权限要求：开发者以上。<br>
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              type: object
              required:
              - name
              - description
              - home_url
              - callback_url
              - type
              - owner
              properties:
                name:
                  type: string
                  description: |
                    应用名<br>
                    以字母开头，由字母、数字、下划线、减号组成，最多32位<br>
                  pattern: '^[a-zA-Z][a-zA-Z0-9_-]{0,31}$'
                  example: 'Violet'
                description:
                  type: string
                  description: 应用简介
                  example: 'A User OAuth2.0 System'
                home_url:
                  type: string
                  description: 应用主页
                  format: url
                  example: 'http://example.com'
                callback_url:
                  type: string
                  description: 应用回调域
                  format: url
                  example: 'http://example.com/callback'
                type:
                  type: number
                  description: 应用分类
                owner:
                  type: string
                  description: 应用所有人，组织名或用户名
                  example: 'XMatrix'
                avatar:
                  type: string
                  description: 应用图标
                  example: 'WE1hdHJpeA=='
      responses:
        '201':
          description: 新建成功
        '400':
          description: 新建失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      exist_name - 应用已存在<br>
                      invalid_avatar - 非法图标<br>
                      invalid_callback_url - 非法回调域<br>
                      invalid_description - 非法简介<br>
                      invalid_home_url - 非法主页<br>
                      invalid_name - 非法名称<br>
                      invalid_owner - 非法所有人<br>
                      invalid_type - 非法类型<br>
                      limit_apps - 应用数量达到上限<br>
                      not_exist_owner - 用户/组织不存在<br>
                      reserved_name - 应用保留<br>
                    example: 'exist_name'
        '401':
          $ref: '#/components/responses/401NotLoginError'
        '403':
          $ref: '#/components/responses/403PermissionDenyError'

  '/orgs':
    post:
      tags: [Organizations]
      summary: 新建组织
      description: |
        权限要求：开发者以上。<br>
        组织名不得与用户名重复。<br>
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              type: object
              required:
              - name
              - description
              - contact
              - email
              - phone
              properties:
                name:
                  type: string
                  description: |
                    组织唯一名称<br>
                    以字母开头，由字母、数字、下划线、减号组成，最多32位<br>
                  pattern: '^[a-zA-Z][a-zA-Z0-9_-]{0,31}$'
                  example: 'XMatrix'
                description:
                  type: string
                  description: 组织简介
                  example: 'Offical Team'
                contact:
                  type: string
                  description: 联系人
                  example: '未知先生'
                email:
                  type: string
                  description: 联系邮箱
                  format: email
                phone:
                  type: string
                  description: 联系电话
                  format: phone
                  example: '12345678901'
      responses:
        '201':
          description: 新建成功
        '400':
          description: 新建失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      exist_name - 用户/组织已存在<br>
                      invalid_contact - 非法联系人<br>
                      invalid_description - 非法简介<br>
                      invalid_email - 非法联系邮箱<br>
                      invalid_name - 非法名称<br>
                      invalid_phone - 非法联系电话<br>
                      limit_orgs - 组织数量达到上限<br>
                      reserved_name - 用户/组织保留<br>
                    example: 'exist_name'
        '401':
          $ref: '#/components/responses/401NotLoginError'
        '403':
          $ref: '#/components/responses/403PermissionDenyError'

  '/users':
    post:
      tags: [Users]
      summary: 注册账号
      description: |
        需验证注册邮箱或注册手机方可进行注册<br>
        该方法可多次请求，直到注册成功或验证状态过期，则验证状态将被删除<br>
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              type: object
              required:
              - name
              - password
              properties:
                name:
                  type: string
                  description: |
                    用户唯一名称<br>
                    以字母开头，由字母、数字、下划线、减号组成，最多32位<br>
                  pattern: '^[a-zA-Z][a-zA-Z0-9_-]{0,31}$'
                  example: 'XMatrix'
                password:
                  type: string
                  description: |
                    用户密码的SHA512散列值<br>
                    密码限制为6-24位，不允许纯数字<br>
                  pattern: '^[a-fA-F0-9]{128}&'
                  example: 'BA3253876AED6BC2...'
                nickname:
                  type: string
                  description: |
                    用户昵称<br>
                    可中英文混合，最多32位<br>
                  pattern: '^([a-zA-Z0-9_-]|\p{Script=Hani})+$'
                  example: '未知矩阵'
      responses:
        '201':
          description: 注册成功
        '400':
          description: 注册失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      exist_name - 用户/组织已存在<br>
                      invalid_name - 非法名称<br>
                      invalid_nickname - 非法昵称<br>
                      invalid_password - 非法密码散列值<br>
                      not_exist_register_record - 不存在注册记录<br>
                      reserved_name - 用户/组织保留<br>
                    example: 'exist_name'
    patch:
      tags: [Users]
      summary: 修改用户个人信息
      description: |
        可用该方法修改密码以及个人信息<br>
        如果两项共同使用，修改密码失败时将不会修改个人信息<br>
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                info:
                  type: object
                  properties:
                    avatar:
                      type: string
                      description: 头像的Base64字符串
                      example: 'WE1hdHJpeA=='
                    bio:
                      type: string
                      description: |
                        个人简历，最多128位<br>
                      example: 'Hello, world!'
                    birthday:
                      type: string
                      description: 生日
                      format: date-time
                    email:
                      type: string
                      description: 联系邮箱
                      format: email
                    gender:
                      type: number
                      description: |
                        性别<br>
                        0 - 未知<br>
                        1 - 男<br>
                        2 - 女<br>
                      enum:
                      - 0
                      - 1
                      - 2
                    location:
                      type: string
                      description: |
                        地址，最多64位<br>
                      example: 'Guangzhou, China'
                    nickname:
                      type: string
                      description: |
                        昵称，最多32位<br>
                      example: '未知矩阵'
                    phone:
                      type: string
                      description: 联系电话
                      format: phone
                      example: '12345678901'
                    url:
                      type: string
                      description: |
                        个人主页，最多128位<br>
                      format: url
                      example: 'https://oauth.xmatrix.studio/'
                secure:
                  type: object
                  required:
                  - old_password
                  - new_password
                  properties:
                    old_password:
                      type: string
                      description: 旧密码的SHA512散列值
                      example: 'BA3253876AED6BC2...'
                    new_password:
                      type: string
                      description: 新密码的SHA512散列值
                      example: '7462482C87F9BAFC...'
      responses:
        '200':
          description: 修改成功
        '400':
          description: 修改失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      error_password - 旧密码错误<br>
                      invalid_avatar - 非法头像Base64字符串<br>
                      invalid_bio - 非法个人简介<br>
                      invalid_birthday - 非法生日<br>
                      invalid_email - 非法联系邮箱<br>
                      invalid_gender - 非法性别<br>
                      invalid_location - 非法地址<br>
                      invalid_new_password - 非法新密码散列值<br>
                      invalid_nickname - 非法昵称<br>
                      invalid_old_password - 非法旧密码散列值<br>
                      invalid_phone - 非法联系电话<br>
                      invalid_url - 非法个人主页<br>
                      same_password - 新旧密码相同<br>
                    example: 'error_password'
        '401':
          $ref: '#/components/responses/401NotLoginError'
          
  '/users/{name}':
    get:
      tags: [Users]
      summary: 获取用户信息
      description: |
        权限要求：游客、登陆用户(仅获取当前用户信息)。<br>
        如果为`me`则获取当前用户信息。<br>
        仅当获取当前用户信息时，才可获取用户登陆邮箱和用户登陆手机以及开发者联系信息。<br>
      parameters:
      - name: name
        in: path
        required: true
        description: 用户名
        schema:
          type: string
          example: 'me'
      responses:
        '200':
          description: 获取成功
          content:
            'application/json':
              schema:
                type: object
                properties:
                  email:
                    type: string
                    description: 用户登陆邮箱
                    format: email
                  phone:
                    type: string
                    description: 用户登陆手机
                    format: phone
                    example: '12345678901'
                  name:
                    type: string
                    description: 用户名
                    example: 'XMatrixStudio'
                  level:
                    type: number
                    description: |
                      用户级别<br>
                      < 0 - 封禁用户<br>
                      0 - 普通用户<br>
                      1 - 开发者<br>
                      50 - 管理员<br>
                      99 - 超级管理员<br>
                    example: 99
                  createTime:
                    type: string
                    description: 用户注册的时间
                    format: date-time
                  info:
                    type: object
                    properties:
                      avatar:
                        type: string
                        description: 头像URL
                        format: url
                        example: 'http://violet-1252808268.cosgz.myqcloud.com/0.png'
                      bio:
                        type: string
                        description: 个人简历
                        example: 'Hello, world!'
                      birthday:
                        type: string
                        description: 生日
                        format: date-time
                      email:
                        type: string
                        description: 联系邮箱
                        format: email
                      gender:
                        type: number
                        description: |
                          性别<br>
                          0 - 未知<br>
                          1 - 男<br>
                          2 - 女<br>
                        enum:
                        - 0
                        - 1
                        - 2
                      location:
                        type: string
                        description: 地址
                        example: 'Guangzhou, China'
                      nickname:
                        type: string
                        description: 昵称
                        example: '未知矩阵'
                      phone:
                        type: string
                        description: 联系电话
                        format: phone
                        example: '12345678901'
                      url:
                        type: string
                        description: 个人主页
                        format: url
                        example: 'https://oauth.xmatrix.studio/'
                  dev:
                    type: object
                    properties:
                      name:
                        type: string
                        description: 联系名称
                        example: '未知先生'
                      email:
                        type: string
                        description: 联系邮箱
                        format: email
                      phone:
                        type: string
                        description: 联系电话
                        format: phone
                        example: '12345678901'
                      app:
                        type: object
                        properties:
                          limit:
                            type: number
                            description: 应用上限
                            example: 10
                          own:
                            type: number
                            description: 当前应用数量
                            example: 3
                      org:
                        type: object
                        properties:
                          limit:
                            type: number
                            description: 组织上限
                            example: 5
                          own:
                            type: number
                            description: 当前组织数量
                            example: 1
                          join:
                            type: number
                            description: 加入组织数量
        '400':
          description: 获取失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      not_found - 用户不存在<br>
                    example: 'not_found'
        '401':
          $ref: '#/components/responses/401NotLoginError'

  '/users/{name}/orgs':
    get:
      tags: [Users]
      summary: 获取组织列表
      description: |
        权限要求：游客、登陆用户(仅指定`user`为`me`)。<br>
      parameters:
      - name: name
        in: path
        required: true
        description: 用户
        schema:
          type: string
      - name: page
        in: query
        description: 页数
        schema:
          type: number
          default: 1
          minimum: 1
      - name: limit
        in: query
        description: 每页资源数量
        schema:
          type: number
          default: 10
          minimum: 1
      responses:
        '200':
          description: 获取成功
          content:
            'application/json':
              schema:
                type: object
                properties:
                  pagination:
                    type: object
                    description: 分页获取信息
                    properties:
                      page:
                        type: number
                        description: 当前页
                        example: 1
                      limit:
                        type: number
                        description: 每页资源数量
                        example: 5
                      total:
                        type: number
                        description: 资源总数
                        example: 1
                  data:
                    type: array
                    description: 组织集合
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: 组织名
                          example: 'XMatrix'
                        description:
                          type: string
                          description: 组织简介
                          example: 'Hello, world~'
                        create_time:
                          type: string
                          description: 创建时间
                          format: date-time
                        avatar:
                          type: string
                          description: 组织头像URL
                          format: url
                          example: 'http://violet-1252808268.cosgz.myqcloud.com/0.png'
        '400':
          description: 获取失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      invalid_limit - 非法每页资源数<br>
                      invalid_page - 非法页码<br>
                      not_exist_user - 用户不存在<br>
                    example: 'not_exist_user'
        '401':
          $ref: '#/components/responses/401NotLoginError'

  '/users/email':
    post:
      tags: [Users]
      summary: 发送邮箱验证邮件
      description: |
        需图形验证放可发送邮箱验证邮件<br>
        该方法不可多次请求，1分钟内仅可发送1次，且每次请求后均删除图形验证状态<br>
        发送邮件是阻塞请求，即只有发送成功或失败该方法才作出响应<br>
        用途包括`register`、`reset`、`update`，其中，<br>
        `register`：注册，仅返回200、400错误；<br>
        `reset`：重置密码，仅返回200、400错误；<br>
        `update`：更新邮箱，仅返回200、400、401、403错误。<br>
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              type: object
              required:
              - operator
              - captcha
              - email
              properties:
                operator:
                  type: string
                  description: 邮箱验证操作的用途
                  enum:
                  - register
                  - reset
                  - update
                captcha:
                  type: string
                  description: 图形验证码
                  example: '1234'
                email:
                  type: string
                  description: 需要验证的邮箱
                  format: email
      responses:
        '201':
          description: 发送验证邮件成功
        '400':
          description: 发送验证邮件失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      通用错误<br>
                      error_captcha - 图形验证码错误<br>
                      invalid_captcha - 非法图形验证码<br>
                      invalid_email - 非法邮箱<br>
                      invalid_operator - 非法操作<br>
                      limit_time - 发送时间间隔限制<br>
                      not_exist_captcha - 不存在图形验证记录<br>
                      send_fail - 发送失败<br>
                      timeout_captcha - 超时图形验证记录<br><br>
                      操作符`register`错误<br>
                      exist_user - 用户已存在<br><br>
                      操作符`reset`错误<br>
                      not_exist_user - 用户不存在<br><br>
                      操作符`update`错误<br>
                      same_email - 邮箱相同<br>
                    example: 'exist_email'
        '401':
          $ref: '#/components/responses/401NotLoginError'
    put:
      tags: [Users]
      summary: 认证邮箱
      description: |
        邮箱验证状态时限为5分钟<br>
        用途包括`register`、`reset`、`update`，其中，<br>
        `register`：注册，仅返回200、400错误；<br>
        `reset`：重置密码，仅返回200、400错误；<br>
        `update`：更新邮箱，仅返回200、400、401、403错误。<br>
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              type: object
              required:
              - operator
              - code
              properties:
                operator:
                  type: string
                  description: 邮箱验证操作的用途
                  enum:
                  - register
                  - reset
                  - update
                code:
                  type: string
                  description: 邮箱验证码
                password:
                  type: string
                  description: 重置密码的SHA512散列值，用于`reset`操作符
              example:
                operator: 'register'
                code: '123456'
      responses:
        '200':
          description: 验证成功
        '400':
          description: 验证失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      error_code - 验证码错误<br>
                      error_operator - 操作错误<br>
                      invalid_code - 非法验证码<br>
                      invalid_operator - 非法操作<br>
                      not_exist_code - 不存在邮箱验证记录<br>
                      timeout_code - 验证码已过期<br>
                    example: 'error_code'
        '401':
          $ref: '#/components/responses/401NotLoginError'

  '/users/levels':
    post:
      tags: [Users]
      summary: 申请更改用户等级
      description: |
        权限要求：普通用户(仅申请开发者)、开发者(仅申请管理员)。<br>
        开发者的申请可自动被接受，管理员的申请需审核。<br>
        超级管理员的申请需在不存在超级管理员的情况方可申请成功。<br>
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              type: object
              required:
              - level
              - name
              - email
              - phone
              properties:
                level:
                  type: number
                  description: |
                    申请的用户等级<br>
                    1 - 开发者<br>
                    50 - 管理员<br>
                    99 - 超级管理员<br>
                name:
                  type: string
                  description: 联系名称
                email:
                  type: string
                  description: 联系邮箱
                phone:
                  type: string
                  description: 联系电话
                remark:
                  type: string
                  description: 备注
              example:
                level: 1
                name: 'X先生'
                email: 'a@xmatrix.studio'
                phone: '12345678901'
                remark: '想要成为开发者'
      responses:
        '201':
          description: 申请成功
        '400':
          description: 申请失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      invalid_email - 非法邮箱<br>
                      invalid_level - 非法等级<br>
                      invalid_name - 非法联系名称<br>
                      invalid_phone - 非法联系电话<br>
                      invalid_remark - 非法备注<br>
                      limit_level - 限制申请的等级<br>
                      not_developer - 非开发者<br>
                      not_normal_user - 非普通用户<br>
                      repeat_request - 重复申请<br>
        '401':
          $ref: '#/components/responses/401NotLoginError'
        '403':
          $ref: '#/components/responses/403PermissionDenyError'

  '/users/levels/apps':
    post:
      tags: [Users]
      summary: 申请提高用户应用上限
      description: |
        权限要求：开发者以上。<br>
        申请如果被接受，应用上限将提高5。<br>
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              type: object
              required:
              - remark
              properties:
                remark:
                  type: string
                  description: |
                    备注，最多256位<br>
                  example: '用于XMatrix开发'
      responses:
        '201':
          description: 申请成功
        '400':
          description: 申请失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      invalid_remark - 非法备注<br>
                      repeat_request - 重复申请<br>
        '401':
          $ref: '#/components/responses/401NotLoginError'
        '403':
          $ref: '#/components/responses/403PermissionDenyError'

  '/users/levels/orgs':
    post:
      tags: [Users]
      summary: 申请提高用户组织上限
      description: |
        权限要求：开发者以上。<br>
        申请如果被接受，组织上限将提高5。<br>
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              type: object
              required:
              - remark
              properties:
                remark:
                  type: string
                  description: |
                    备注，最多256位<br>
                  example: '用于XMatrix开发'
      responses:
        '201':
          description: 申请成功
        '400':
          description: 申请失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      invalid_remark - 非法备注<br>
                      repeat_request - 重复申请<br>
        '401':
          $ref: '#/components/responses/401NotLoginError'
        '403':
          $ref: '#/components/responses/403PermissionDenyError'

  '/users/phone':
    post:
      tags: [Users]
      summary: 发送手机验证短信，验证码固定为123456
      deprecated: true
      description: |
        需图形验证放可发送手机验证短信<br>
        该方法不可多次请求，1分钟内仅可发送1次，且每次请求后均删除图形验证状态<br>
        发送短信是阻塞请求，即只有发送成功或失败该方法才作出响应<br>
        用途包括`register`、`reset`、`update`，其中，<br>
        `register`：注册，仅返回200、400错误；<br>
        `reset`：重置密码，仅返回200、400错误；<br>
        `update`：更新手机，仅返回200、400、401、403错误。<br>
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              type: object
              required:
              - operator
              - captcha
              - phone
              properties:
                operator:
                  type: string
                  description: 手机验证操作的用途
                  enum:
                  - register
                  - reset
                  - update
                captcha:
                  type: string
                  description: 图形验证码
                  example: '1234'
                phone:
                  type: string
                  description: 需要验证的手机
                  format: phone
                  example: '12345678901'
      responses:
        '201':
          description: 发送验证短信成功
        '400':
          description: 发送验证短信失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      通用错误<br>
                      error_captcha - 图形验证码错误<br>
                      invalid_captcha - 非法图形验证码<br>
                      invalid_operator - 非法操作<br>
                      invalid_phone - 非法手机号码<br>
                      limit_time - 发送时间间隔限制<br>
                      not_exist_captcha - 不存在图形验证记录<br>
                      send_fail - 发送失败<br>
                      timeout_captcha - 超时图形验证记录<br><br>
                      操作符`register`错误<br>
                      exist_user - 用户已存在<br><br>
                      操作符`reset`错误<br>
                      not_exist_user - 用户不存在<br><br>
                      操作符`update`错误<br>
                      same_phone - 手机号码相同<br>
                    example: 'exist_email'
        '401':
          $ref: '#/components/responses/401NotLoginError'
    put:
      tags: [Users]
      summary: 认证手机
      description: |
        手机验证状态时限为5分钟<br>
        用途包括`register`、`reset`、`update`，其中，<br>
        `register`：注册，仅返回200、400错误；<br>
        `reset`：重置密码，仅返回200、400错误；<br>
        `update`：更新手机，仅返回200、400、401、403错误。<br>
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              type: object
              required:
              - operator
              - code
              properties:
                operator:
                  type: string
                  description: 手机验证操作的用途
                  enum:
                  - register
                  - reset
                  - update
                code:
                  type: string
                  description: 手机验证码
                password:
                  type: string
                  description: 重置密码的SHA512散列值，用于`reset`操作符
              example:
                operator: 'register'
                code: '123456'
      responses:
        '200':
          description: 验证成功
        '400':
          description: 验证失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      error_code - 验证码错误<br>
                      error_operator - 操作错误<br>
                      invalid_code - 非法验证码<br>
                      invalid_operator - 非法操作<br>
                      not_exist_code - 不存在邮箱验证记录<br>
                      timeout_code - 验证码已过期<br>
                    example: 'error_code'
        '401':
          $ref: '#/components/responses/401NotLoginError'

  '/users/session':
    post:
      tags: [Users]
      summary: 登陆账号
      description: |
        使用用户名、登陆邮箱、登陆手机等唯一标识之一登陆<br>
        普通登陆身份验证有效时限为1天，且以上一次有效请求开始计时<br>
        自动登陆身份验证有效时限为15天<br>
        如果登陆失败超过3次，将在半个小时内禁止登陆，该限制可通过重置密码解除<br>
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              type: object
              required:
              - user
              - password
              properties:
                user:
                  type: string
                  description: 用户唯一标识，可以是用户名或邮箱或手机
                  example: 'XMatrix'
                password:
                  type: string
                  description: 用户密码的SHA512散列值
                  example: 'BA3253876AED6BC2...'
                remember:
                  type: boolean
                  description: 是否自动登陆
      responses:
        '201':
          description: 登陆成功
        '400':
          description: 登陆失败
          content:
            'application/json':
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      error_user_or_password - 用户唯一标识或密码错误<br>
                      invalid_email - 非法邮箱<br>
                      invalid_name - 非法用户名<br>
                      invalid_password - 非法密码散列值<br>
                      invalid_user - 非法用户唯一标识<br>
                      limit_error_count - 登陆错误次数上限<br>
                    example: 'error_user_or_password'
    delete:
      tags: [Users]
      summary: 登出账号
      description: 该方法响应固定成功，即使未登陆
      responses:
        '204':
          description: 登出成功

  '/util/captcha':
    get:
      tags: [Util]
      summary: 获取图形验证码
      description: |
        用于图形验证码的获取，返回png格式的验证码图形的Base64字符串，其中验证码为4位数字<br>
        该接口用于邮箱验证、手机验证，有效期为5分钟<br>
      responses:
        '200':
          description: 获取成功
          content:
            'text/plain':
              schema:
                type: string
              example:
                data:image/png;base64,iVBORw0KGgoAAAAN...
